language: java
jdk:
 - oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: app-diego-learning
addons:
  sonarcloud:
    organization: "diegunix-github"
    token:
      secure: $SONAR_TOKEN
script:
  - sonar-scanner
